<html>
<head>
<title>PyErr_Fetch</title>
<meta name='robots' content='noindex,nofollow'>
<meta name='generator' content='GLOBAL-5.8.1'>
</head>
<body text='#191970' bgcolor='#f5f5dc' vlink='gray'>
<pre>
<a href='../S/2250.html#L939'>PyErr_Fetch</a>       939 Modules/_ctypes/callproc.c     PyErr_Fetch(&amp;tp, &amp;v, &amp;tb);
<a href='../S/2570.html#L613'>PyErr_Fetch</a>       613 Modules/_io/bufferedio.c     PyErr_Fetch(&amp;t, &amp;v, &amp;tb);
<a href='../S/2572.html#L82'>PyErr_Fetch</a>        82 Modules/_io/fileio.c         PyErr_Fetch(&amp;exc, &amp;val, &amp;tb);
<a href='../S/2573.html#L209'>PyErr_Fetch</a>       209 Modules/_io/iobase.c     PyErr_Fetch(&amp;tp, &amp;v, &amp;tb);
<a href='../S/2575.html#L2291'>PyErr_Fetch</a>      2291 Modules/_io/textio.c         PyErr_Fetch(&amp;type, &amp;value, &amp;traceback);
<a href='../S/2578.html#L391'>PyErr_Fetch</a>       391 Modules/_lsprof.c     PyErr_Fetch(&amp;last_type, &amp;last_value, &amp;last_tb);
<a href='../S/2618.html#L1232'>PyErr_Fetch</a>      1232 Modules/_tkinter.c         PyErr_Fetch(e-&gt;exc_type, e-&gt;exc_value, e-&gt;exc_tb);
<a href='../S/2618.html#L1539'>PyErr_Fetch</a>      1539 Modules/_tkinter.c         PyErr_Fetch(&amp;exc, &amp;val, &amp;tb);
<a href='../S/2618.html#L1996'>PyErr_Fetch</a>      1996 Modules/_tkinter.c     PyErr_Fetch(&amp;excInCmd, &amp;valInCmd, &amp;trbInCmd);
<a href='../S/2618.html#L2267'>PyErr_Fetch</a>      2267 Modules/_tkinter.c         PyErr_Fetch(&amp;excInCmd, &amp;valInCmd, &amp;trbInCmd);
<a href='../S/2618.html#L2467'>PyErr_Fetch</a>      2467 Modules/_tkinter.c         PyErr_Fetch(&amp;excInCmd, &amp;valInCmd, &amp;trbInCmd);
<a href='../S/2623.html#L72'>PyErr_Fetch</a>        72 Modules/atexitmodule.c             PyErr_Fetch(&amp;exc_type, &amp;exc_value, &amp;exc_tb);
<a href='../S/2698.html#L256'>PyErr_Fetch</a>       256 Modules/pyexpat.c     PyErr_Fetch(&amp;type, &amp;value, &amp;traceback);
<a href='../S/2711.html#L2948'>PyErr_Fetch</a>      2948 Modules/socketmodule.c         PyErr_Fetch(&amp;exc, &amp;val, &amp;tb);
<a href='../S/2787.html#L732'>PyErr_Fetch</a>       732 Objects/dictobject.c         PyErr_Fetch(&amp;err_type, &amp;err_value, &amp;err_tb);
<a href='../S/2792.html#L864'>PyErr_Fetch</a>       864 Objects/frameobject.c     PyErr_Fetch(&amp;error_type, &amp;error_value, &amp;error_traceback);
<a href='../S/2792.html#L911'>PyErr_Fetch</a>       911 Objects/frameobject.c     PyErr_Fetch(&amp;error_type, &amp;error_value, &amp;error_traceback);
<a href='../S/2794.html#L161'>PyErr_Fetch</a>       161 Objects/genobject.c     PyErr_Fetch(&amp;error_type, &amp;error_value, &amp;error_traceback);
<a href='../S/2824.html#L5339'>PyErr_Fetch</a>      5339 Objects/typeobject.c     PyErr_Fetch(&amp;error_type, &amp;error_value, &amp;error_traceback);
<a href='../S/2830.html#L896'>PyErr_Fetch</a>       896 Objects/weakrefobject.c             PyErr_Fetch(&amp;err_type, &amp;err_value, &amp;err_tb);
<a href='../S/2830.html#L915'>PyErr_Fetch</a>       915 Objects/weakrefobject.c                     PyErr_Fetch(&amp;err_type, &amp;err_value, &amp;err_tb);
<a href='../S/3089.html#L111'>PyErr_Fetch</a>       111 Python/ast.c       PyErr_Fetch(&amp;type, &amp;value, &amp;tback);
<a href='../S/3089.html#L1370'>PyErr_Fetch</a>      1370 Python/ast.c                   PyErr_Fetch(&amp;type, &amp;value, &amp;tback);
<a href='../S/3091.html#L1233'>PyErr_Fetch</a>      1233 Python/ceval.c         PyErr_Fetch(&amp;error_type, &amp;error_value, &amp;error_traceback);
<a href='../S/3091.html#L2966'>PyErr_Fetch</a>      2966 Python/ceval.c                 PyErr_Fetch(&amp;exc, &amp;val, &amp;tb);
<a href='../S/3091.html#L3523'>PyErr_Fetch</a>      3523 Python/ceval.c     PyErr_Fetch(&amp;type, &amp;value, &amp;traceback);
<a href='../S/3091.html#L3550'>PyErr_Fetch</a>      3550 Python/ceval.c     PyErr_Fetch(&amp;type, &amp;value, &amp;traceback);
<a href='../S/3106.html#L171'>PyErr_Fetch</a>       171 Python/errors.c         PyErr_Fetch(&amp;exception, &amp;value, &amp;tb);
<a href='../S/3106.html#L276'>PyErr_Fetch</a>       276 Python/errors.c     PyErr_Fetch(exc, val, tb);
<a href='../S/3106.html#L711'>PyErr_Fetch</a>       711 Python/errors.c     PyErr_Fetch(&amp;t, &amp;v, &amp;tb);
<a href='../S/3106.html#L779'>PyErr_Fetch</a>       779 Python/errors.c     PyErr_Fetch(&amp;exc, &amp;v, &amp;tb);
<a href='../S/3138.html#L1389'>PyErr_Fetch</a>      1389 Python/pythonrun.c     PyErr_Fetch(&amp;exception, &amp;value, &amp;tb);
<a href='../S/3138.html#L1438'>PyErr_Fetch</a>      1438 Python/pythonrun.c     PyErr_Fetch(&amp;exception, &amp;v, &amp;tb);
<a href='../S/3138.html#L1464'>PyErr_Fetch</a>      1464 Python/pythonrun.c             PyErr_Fetch(&amp;exception2, &amp;v2, &amp;tb2);
<a href='../S/3138.html#L1729'>PyErr_Fetch</a>      1729 Python/pythonrun.c     PyErr_Fetch(&amp;type, &amp;value, &amp;traceback);
<a href='../S/3138.html#L2030'>PyErr_Fetch</a>      2030 Python/pythonrun.c         PyErr_Fetch(&amp;type, &amp;value, &amp;tb);
<a href='../S/3144.html#L2013'>PyErr_Fetch</a>      2013 Python/sysmodule.c     PyErr_Fetch(&amp;error_type, &amp;error_value, &amp;error_traceback);
<a href='../S/3144.html#L2055'>PyErr_Fetch</a>      2055 Python/sysmodule.c     PyErr_Fetch(&amp;error_type, &amp;error_value, &amp;error_traceback);
<a href='../S/3156.html#L382'>PyErr_Fetch</a>       382 Python/traceback.c         PyErr_Fetch(&amp;exc_type, &amp;exc_value, &amp;exc_tb);
</pre>
</body>
</html>
