<html>
<head>
<title>PyErr_NormalizeException</title>
<meta name='robots' content='noindex,nofollow'>
<meta name='generator' content='GLOBAL-5.8.1'>
</head>
<body text='#191970' bgcolor='#f5f5dc' vlink='gray'>
<pre>
<a href='../S/2250.html#L940'>PyErr_NormalizeException</a>  940 Modules/_ctypes/callproc.c     PyErr_NormalizeException(&amp;tp, &amp;v, &amp;tb);
<a href='../S/2618.html#L1540'>PyErr_NormalizeException</a> 1540 Modules/_tkinter.c         PyErr_NormalizeException(&amp;exc, &amp;val, &amp;tb);
<a href='../S/2623.html#L75'>PyErr_NormalizeException</a>   75 Modules/atexitmodule.c                 PyErr_NormalizeException(&amp;exc_type, &amp;exc_value, &amp;exc_tb);
<a href='../S/2794.html#L237'>PyErr_NormalizeException</a>  237 Objects/genobject.c         PyErr_NormalizeException(&amp;typ, &amp;val, &amp;tb);
<a href='../S/3091.html#L2971'>PyErr_NormalizeException</a> 2971 Python/ceval.c                 PyErr_NormalizeException(
<a href='../S/3106.html#L298'>PyErr_NormalizeException</a>  298 Python/errors.c     PyErr_NormalizeException(exc, val, tb);
<a href='../S/3106.html#L780'>PyErr_NormalizeException</a>  780 Python/errors.c     PyErr_NormalizeException(&amp;exc, &amp;v, &amp;tb);
<a href='../S/3138.html#L1441'>PyErr_NormalizeException</a> 1441 Python/pythonrun.c     PyErr_NormalizeException(&amp;exception, &amp;v, &amp;tb);
<a href='../S/3138.html#L1465'>PyErr_NormalizeException</a> 1465 Python/pythonrun.c             PyErr_NormalizeException(&amp;exception2, &amp;v2, &amp;tb2);
</pre>
</body>
</html>
