<html>
<head>
<title>PyTrace_EXCEPTION</title>
<meta name='robots' content='noindex,nofollow'>
<meta name='generator' content='GLOBAL-5.8.1'>
</head>
<body text='#191970' bgcolor='#f5f5dc' vlink='gray'>
<pre>
<a href='../S/2698.html#L266'>PyTrace_EXCEPTION</a>  266 Modules/pyexpat.c     err = trace_frame(tstate, f, PyTrace_EXCEPTION, arg);
<a href='../S/3091.html#L3533'>PyTrace_EXCEPTION</a> 3533 Python/ceval.c     err = call_trace(func, self, f, PyTrace_EXCEPTION, arg);
</pre>
</body>
</html>
